### ISSUE TITLE
Unable to run on termux

### ISSUE THREAD

**Issue by t-e-s-tweb** [fireinrain/cf-speedtester#1]
I built it using go build.  Binary is created but running it only gives 
./cf: line 1: syntax error near unexpected token `newline'
./cf: line 1: `!<arch>'

**Comment by fireinrain** [comment]
haha, this is an sdk for golang, so you cant build it directly and run. you should create an golang project, and add this lib as a dependency, then in your project, you can call the cloudflare speed test function.
